

services:
  pygeoapi:
    build: .
    # image: pygeo-opentel:latest

    container_name: pygeoapi

    ports:
      - 5000:80

    volumes:
      - ./pygeoapi.config.yml:/pygeoapi/local.config.yml
      - ./data:/data
      - ./plugins/process/squared.py:/pygeoapi/pygeoapi/process/squared.py
      - ./plugins/process/localoutlier.py:/pygeoapi/pygeoapi/process/localoutlier.py
      - ./plugins/process/aanvraag.py:/pygeoapi/pygeoapi/process/aanvraag.py
