---
id: amstelveen
title: OGC API Demo Service
description: OGC APIs are constructed as "building blocks" that can be used to assemble novel APIs for web access to geospatial content
metadata:
  contactName: Jane Doe
  contactEmail: doe@acme.nl
  creatorName: Then big creator
  creatorUrl: https://data.somewhere.nl/
  publisherName: Acme Inc.
  publisherUrl: https://www.example.com/
  licenseName: CC0 1.0
  licenseUrl: http://creativecommons.org/publicdomain/zero/1.0/deed.nl
  attribution: 'data from somewhere'
api:
- buildingBlock: CRS
  enabled: true
  additionalCrs:
  - code: 25832
    forceAxisOrder: NONE
  - code: 4258
    forceAxisOrder: NONE
  - code: 4326
    forceAxisOrder: NONE
  - code: 3857
    forceAxisOrder: NONE
